# Uncomment the next line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '10.0'

target 'Pray111_beta_0.2' do


  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SideMenu'
  pod 'DynamicCodable', '1.0'


  
  # add the Firebase pod for Google Analytics

  # add pods for any other desired Firebase products
  
  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 카카오 로그인
  pod 'KakaoSDKUser'  # 사용자 관리
  pod 'KakaoSDKTalk'  # 친구, 메시지(카카오톡)
  # pod 'KakaoSDKStory'  # 카카오스토리
  pod 'KakaoSDKLink'  # 메시지(카카오링크)
  pod 'KakaoSDKTemplate'  # 메시지 템플릿

  # Pods for Pray111_beta_0.2

end
