# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'recordAudio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'IQAudioRecorderController'

  # Pods for recordAudio

  target 'recordAudioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'recordAudioUITests' do
    # Pods for testing
  end

end
